### ISSUE TITLE
Need a way to detect loss of power before the capacitors finish discharging

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-electronics#19]
Assuming we get anywhere close to the 100ms of run time off of the capacitor, we need to be able to sense the power loss so that we can gracefully flush the disks to avoid disk corruption.

**Comment by BrianAdams** [comment]
How big of a can of worms would it be to incorporate a backup battery on to the beaglebone so that we can always gracefully shutdown?

**Comment by WaltHolm** [comment]
A feature was implemented in Controller Board 2.8 to signal the ATmega2560 (Arduino) processor ~100msec before power is shut down
