### ISSUE TITLE
Enable external LED capability to the board

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-electronics#23]
Add wiring from PWM3 to external TB20 and TB21 to support external LEDs
Stuff R32 to enable PWM3 from the factory

**Comment by WaltHolm** [comment]
Done in Controller Board 2.8.   There are 0-ohm resistors in the PWM3 traces to TP20 and TP21, so that PWM3 can be disconnected from TP20 and TP21 if desired
