### ISSUE TITLE
Improve filtering on current measurement telemetry points

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-electronics#27]
Telemetry of the current measurements is very noisy due to undersampling.  Reduce the corner frequency of the filtering to smooth out this data.

**Comment by BrianAdams** [comment]
Currently no filter on the Battery tubes
ESCs have .1uf and 10k ~150hz, Should slow the corner frequency to about 50hz to target a 100hz sample rate.

**Comment by WaltHolm** [comment]
On Controller board 2.8, filtering was added on Battery Current measurement points.  Corner frequency on all current measuring points was lowered to 50 Hz.
