### ISSUE TITLE
Use Aux1 and Aux2 with other voltage sources

### ISSUE THREAD

**Issue by ThomasSo** [OpenROV/openrov-electronics#5]
I could be a benefit for some users to change the power source for AUX1 & 2 from 12V_REG to V_BAT or other external power-source.
This is mostly for users that want to use higher than 12V to drive  equipment on AUX1 & 2
This also applies when the load on Aux exceeds the 1Amp spec. of the 12V regulator.

**Comment by BrianAdams** [comment]
Done as of controllerboard 2.5
